### ISSUE TITLE
Problem with legacy code

### ISSUE THREAD

**Issue by aljosahafner** [dmpelt/pymrfbp#3]
Hello,

I've been updating and re-maintaining some legacy tomography code which contains this implementation of PyMR-FBP as well. However, my code contains the following calls:

```
import mrfbp

mrfbp.ASTRAProjector.ASTRAProjector2D(proj_geom,vol_geom)
mrfbp.Reconstructor(p)
```

The error is:
```
AttributeError: module 'mrfbp' has no attribute 'ASTRAProjector'
```

The pymrfbp package has been installed from the pymrfb root folder using:
```
pip install -e .
```

Do you have any idea why this happens and how can this be overcome. I am sure there is an easy and elegant solution, but I am failing to see it ... Thanks in advance for your help!

**Comment by dmpelt** [comment]
Hi!

I think the code you are using is using an old version of the MRFBP implementation. The current implementation uses the ASTRA toolbox plugin system to initialize and call the MRFBP algorithm, as described here: https://github.com/dmpelt/pymrfbp/blob/master/examples/ASTRAExample.py .

I hope this helps!

**Comment by aljosahafner** [comment]
Hello,

Thanks a lot for your answer. I already figured it out by now and indeed I have used the example you linked above to fix the code.

Cheers!
